/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JdgQuickView.java
 *
 * Created on Nov 29, 2013, 6:46:34 AM
 */
package com.tafadzwa.moyo.insurance.module.risk;

import com.innate.cresterp.insurance.risk.entities.Risk;



/**
 *
 * @author Tafadzwa
 */
public class JdgQuickView extends javax.swing.JDialog {

    private Risk risk ;
    /** Creates new form JdgQuickView */
    public JdgQuickView(java.awt.Frame parent, boolean modal, Risk risk) {
        super(parent, modal);
        initComponents();
        this.risk = risk;
        postInit();
    }
    
    private void postInit(){
        
        StringBuilder sb = new StringBuilder();
        
        sb.append(" Insured: ").append(risk.getClient().getName()).append(" ").append(risk.getClient().getSurname());
        sb.append("\n\n Insurer: ").append(risk.getInsurer().getName());
        sb.append("\n\n Type: ").append(risk.getPolicyType().getPolicyType());
        sb.append("\n\n Inception: ").append(risk.getPolicyPeriod().getInception());
        sb.append("\n Expiry: ").append(risk.getPolicyPeriod().getExpiry());
        sb.append("\n Renewal: ").append(risk.getPolicyPeriod().getRenewal());
        sb.append("\n Effective: ").append(risk.getPolicyPeriod().getEffectiveDate());
        sb.append("\n Transaction Date: ").append(risk.getPolicyPeriod().getTransactionDate());
        sb.append("\n\n Description: ").append(risk.getDescription());
        sb.append("\n\n Cover Note: ").append(risk.getCoverNoteNumber());
        sb.append("\n\n Basic Premium: ").append(risk.getRiskPremium().getBasicPremium());
        sb.append("\n\n Annual Premium: ").append(risk.getRiskPremium().getAnnualPremium());
        sb.append("\n\n Insurer Premium: ").append(risk.getRiskPremium().getPremiumNet());
          
        jTextArea1.append(sb.toString());
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JdgQuickView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JdgQuickView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JdgQuickView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JdgQuickView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                JdgQuickView dialog = new JdgQuickView(new javax.swing.JFrame(), true,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
