/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * JdgQuickView.java
 *
 * Created on Nov 29, 2013, 6:46:34 AM
 */
package com.innate.erp.broking.claims;

import com.innate.cresterp.insurance.risk.entities.Claim;



/**
 *
 * @author Tafadzwa
 */
public class JdgQuickView extends javax.swing.JDialog {

    private Claim claim ;
    /** Creates new form JdgQuickView */
    public JdgQuickView(java.awt.Frame parent, boolean modal, Claim claim) {
        super(parent, modal);
        initComponents();
        this.claim = claim;
        postInit();
        
    }
    
    private void postInit(){
        
        StringBuilder sb = new StringBuilder();
        
        sb.append(" Insured: ").append(claim.getClaimPolicy().getClient().getName()).
                append(" ").append(claim.getClaimPolicy().getClient().getSurname());
        sb.append("\n\n Insurer: ").append(claim.getClaimPolicy().getInsurer().getName());
        sb.append("\n\n Claimant: ").append(claim.getClaimant());
        sb.append("\n\n Claim Type: ").append(claim.getClaimType().getValue());
        sb.append("\n\n Registration: ").append(claim.getRegistrationDate());
        sb.append("\n Date Submitted: ").append(claim.getDatesubmittedNotification());
        sb.append("\n Date Of Loss: ").append(claim.getDateOfLoss());
        sb.append("\n Followup Date: ").append(claim.getFollowUpDate());
        sb.append("\n\n Process Status: ").append(claim.getClaimStatus().getValue());
        sb.append("\n\n Remarks: ").append(claim.getRemarks());
        sb.append("\n\n Gross Claim: ").append(claim.getGrossClaim());
        sb.append("\n\n Excess: ").append(claim.getExcess());
        sb.append("\n\n Betterment: ").append(claim.getBetterment());
        sb.append("\n\n Net Claim: ").append(claim.getNetClaim());
        sb.append("\n\n Claim Status: ").append(claim.getPremiumStatus().getValue());
          
        jTextArea1.append(sb.toString());
       
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jScrollPane1 = new javax.swing.JScrollPane();
        jTextArea1 = new javax.swing.JTextArea();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);

        jTextArea1.setColumns(20);
        jTextArea1.setRows(5);
        jScrollPane1.setViewportView(jTextArea1);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 568, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 442, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JdgQuickView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JdgQuickView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JdgQuickView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JdgQuickView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the dialog */
        java.awt.EventQueue.invokeLater(new Runnable() {

            public void run() {
                JdgQuickView dialog = new JdgQuickView(new javax.swing.JFrame(), true,null);
                dialog.addWindowListener(new java.awt.event.WindowAdapter() {

                    @Override
                    public void windowClosing(java.awt.event.WindowEvent e) {
                        System.exit(0);
                    }
                });
                dialog.setVisible(true);
            }
        });
    }
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTextArea jTextArea1;
    // End of variables declaration//GEN-END:variables
}
